name: sowi
description: "A new Flutter project."
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  svg_path_parser: ^1.1.2
  window_manager: ^0.4.3
dev_dependencies:
  lint: ^2.3.0
flutter:
  assets:
    - assets/
    - assets/characters/
